[workspace]
members = [
  "crates/learn",
]

# warning: some crates are on edition 2021 which defaults to `resolver = "2"`,
# but virtual workspaces default to `resolver = "1"`.
# to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
resolver = "2"
